- name: Install base packages
  yum:
    name:
      - git
      - unzip
    state: present

- name: Install Node.js 18
  shell: |
    curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
    yum install -y nodejs
  args:
    executable: /bin/bash

- name: Install PM2 globally
  npm:
    name: pm2
    global: yes

- name: Install Java 21
  yum:
    name: java-21-amazon-corretto
    state: present
