- name: Install Jenkins repo
  shell: |
    wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
    rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
  args:
    executable: /bin/bash

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Stop Jenkins
  service:
    name: jenkins
    state: stopped

- name: Remove old Jenkins
  file:
    path: /var/lib/jenkins
    state: absent

# 🔥 Backup copy
- name: Copy Jenkins backup
  copy:
    src: "{{ playbook_dir }}/../jenkins/jenkins-full-backup.tar.gz"
    dest: /tmp/jenkins.tar.gz

- name: Restore backup
  unarchive:
    src: /tmp/jenkins.tar.gz
    dest: /var/lib/
    remote_src: yes

# 🔥 FIX WORKER NODE IP
- name: Update worker IP in Jenkins node config
  replace:
    path: /var/lib/jenkins/nodes/agent-b/config.xml
    regexp: '<host>.*</host>'
    replace: '<host>{{ worker_private_ip }}</host>'

# 🔥 FIX SSH PRIVATE KEY
- name: Update SSH private key in Jenkins credentials
  replace:
    path: /var/lib/jenkins/credentials.xml
    regexp: '<privateKey>.*</privateKey>'
    replace: '<privateKey>{{ private_key }}</privateKey>'

- name: Fix permissions
  file:
    path: /var/lib/jenkins
    owner: jenkins
    group: jenkins
    recurse: yes

# 🔥 Restart Jenkins to apply changes
- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted
    enabled: yes
