app_name: backend_A

# clone full repo here
app_dir: /opt/opt_repo

repo_url: "https://github.com/hussainmahammad/opt.git"
branch: "main"

# actual app path inside repo
backend_path: "{{ app_dir }}/apps/backend"

start_file: "server.js"
